Profile/urls.py
from django.urls import include, re_path
from Profile.views import ProfileView  ,ShopadminView , shop, favouriteshops,AboutView 
from .import views
from .views import  ShopFormView  , ClientFormUpdate ,ClientFormView, ShopFormUpdate

from shopp.views import delete_view, Resident_detailView
app_name='Profile'

urlpatterns = [
    re_path(r'^Profile/$', ProfileView.as_view(), name='Profile'),
    re_path(r'^Profile/(?P<pk>\d+)/$', ProfileView.as_view(), name='view_profile_with_pk'),
    re_path(r'^editclient/$', ClientFormUpdate.as_view(), name='editclient'),
    re_path(r'^Shopadmin/$', ShopadminView.as_view(), name='Shopadmin'),
    re_path(r'^shop/$', views.shop, name='shop'),
    re_path(r'^favouriteshops/$', views.favouriteshops, name='favouriteshops'),
    re_path(r'^about', AboutView.as_view(), name='about'),
    re_path(r'^(?P<uniqueadress>\d+)/(?P<date>[-\w]+)/$', Resident_detailView.as_view(), name='detail'),
    #re_path(r'^Profile/(?P<id>\d+)/(?P<slug>[-\w]+)/$', ProfileView.as_view(), name='user_post_detail'),
    #re_path('product_form/', ProductFormView.as_view(), name = 'product_form'),
    re_path('shopform/', ShopFormView.as_view(), name='Shopform'),
    re_path('clientform/', ClientFormView.as_view(), name='Clientform'),
    re_path(r'^editshop/$', ShopFormUpdate.as_view(), name = 'editshop' )
    
]

estate/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include ,path ,re_path


from login.views import  client , shop, login

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('home/',include('home.urls',namespace='home')),
    #path('main/',include('main.urls',namespace='main')),
    re_path(r'', include('shopp.urls',namespace='shop')),
    path('', include('login.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', login.SignUpView.as_view(), name='signup'),
    path('accounts/signup/client/', client.ClientSignUpView.as_view(), name='client_signup'),
    path('accounts/signup/shop/', shop.ShopSignUpView.as_view(), name='shop_signup'),
    #path('shopp/',include('shopp.urls',namespace='shop')),
    path('Profile/',include('Profile.urls',namespace='Profile')),
    
    
]
   
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   

home/urls.py
from django.conf.urls import url
from django.urls import include, re_path
#from home.views import 
from django.contrib.auth import views as auth_views
from . import views as myapp_views
from home import views
from . import views 
from home.views import ContactView, PrivacyView, TermsView, MarkersMapView, AboutView, HomeView, coordinates_form, maps #, map, route


app_name = 'home'


urlpatterns = [
    re_path(r'^$', HomeView.as_view(), name='home'),
    re_path(r'^privacy/', PrivacyView.as_view(), name='privacy' ),
    re_path(r'^terms/', TermsView.as_view(), name='terms'),
    #re_path(r"^map/", MarkersMapView.as_view(),name="map"),
    #re_path(r'^route/', views.route, name="route"),
    re_path(r'^coordinates-form/',views.coordinates_form, name = 'coordinates-form'),
    re_path(r'^map/', views.maps, name="map"),
    
    re_path(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$', 
            views.change_friends, name='change_friends'),
    re_path('contact/', ContactView.as_view(), name='Contact'),
    re_path(r'^about/', AboutView.as_view(), name='about'),

  
]

shopp/urls.py
from django.conf.urls import include, re_path
from .import views
from .views import  AbouttView,  all_shops
from shopp.views import Product_detailView, ShopsView, delete_view, product_delete_view, BusinessAdressFormView,Product_detailView,ResidentAddressFormView
#from Profile.views import ProductDeleteView


app_name = 'shopp'

urlpatterns = [
    re_path(r'^$', views.product_list, name='product_list'),
    #re_path(r'^(?P<id>\d+)/delete/', views.product_list, name='product_list'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    re_path('^<int:id>/delete/$', product_delete_view, name='product_delete'),
    re_path(r'^$', ShopsView.as_view(), name='shops'),
    re_path('shopp/businessadress_form/', BusinessAdressFormView.as_view(), name='businessadress_form'),
    re_path('shopp/residentadressform/', ResidentAddressFormView.as_view(), name='residentadressform'),
    re_path(r'^(?P<uniqueadress>\d+)/(?P<slug>[-\w]+)/$', Product_detailView.as_view(), name='business_detail'),
    #re_path(r'^(?P<pk>\d+)/(?P<slug>[-\w]+)/$', Product_detailView.as_view(), name='business_detail_with_pk'),
    re_path(r'^about_uss/$',views.AbouttView, name='about_uss'),
    re_path(r'^contact_us/$', views.contact_us , name='contact_us'),
    re_path(r'^registershop/$', views.registershop, name='registershop'), 
    
    re_path(r'^search/$', views.search, name='search'),  
    re_path(r'^all_shops/$', views.all_shops, name='all_shops'),
    #re_path(r'^<int:product_pk>/(?P<slug>[-\w]+)/delete/',ProductDeleteView.as_view(), name='product_delete'),
    

    
]

Profile/forms.py
from django import forms
from login.models import User, Shop, Client
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
#the models for these forms are in login.// rhis form has been put here as an extension
class ShopForm(forms.ModelForm):

    class Meta:
        model = Shop

        fields = [
            
            
            'Industry',
            'description',
            'county',
            'building',
            
            'phone',
            'image',
            'street',
        ]

    def save(self, user=None):
        shop = super(ShopForm, self).save(commit=False)
        if user:
            shop.user = user
        shop.save()
        return shop




class ClientForm(forms.ModelForm):

    class Meta:
        model = Client
       # model = User

        fields = [
            
            'phone',
            'county',
            'image',
            'street',
            'building',
            
        ]

    def save(self, user=None):
        client = super(ClientForm, self).save(commit=False)
        if user:
            client.user = user
        client.save()
        return client

Profile/views.py
from django.views.generic import TemplateView
from django.http import Http404
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from login.models import User, Client, Shop
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.views.generic import (ListView, UpdateView, CreateView, FormView, DeleteView)
from django.utils.decorators import method_decorator
from shopp.models import Shop
from django.core.paginator import Paginator
from Profile.models import About
from types import MethodType
from operator import attrgetter
#from shopp.forms import ProductForm
from Profile.forms import ShopForm, ClientForm
from login.decorators import shop_required, client_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from home.models import Friend
from django.urls import reverse_lazy 
from random import randint
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from shopp.models import BusinessAddress

#this is the view that helps users to view shops either theirs or others!!! it has pk that diffrentiates between the two
class ProfileView(TemplateView):
    template_name = 'Profile/Profile.html'
    
    def get(self, request, category_slug=None, pk=None):
        category = None
        context = {}

        if pk:
           
            user = User.objects.get(pk=pk)
            business = BusinessAddress.objects.filter(user=user).order_by('-date')
            print(business)
            
        else:
            category = None
            user = request.user
            business = BusinessAddress.objects.filter(user=request.user.id).order_by('-date')
            print(business)
        args = { 
                 'user' : user,
                  'business' : business,
                 
                 
        }   
          


       
        

   
       
        return render(request, self.template_name, args)

#end view 

#about view
class AboutView(TemplateView):
    template_name = 'Profile/about.html'

    def get(self, request):
        about = About.objects.all()
        
        args = {'about': about}
        return render(request, self.template_name, args)

#end about
 
#view that shows favourite shops
def favouriteshops(request):

    try:
        #users = User.objects.exclude(id=request.user.id)
        users = User.objects.all()
        friend = Friend.objects.get(current_user=request.user)
        friends = friend.users.all()
    except:
        users = User.objects.all()
        friends = print("no favourites!!!")

    return render (request, 'Profile/favourites.html', {'users':users,'friends': friends  })

#end view

#view that shows all  shops, this view was originally a class but changed to accomodate pagination which later should be returned to a class
#@login_required
def shop(request, category_slug=None):

    business = BusinessAddress.objects.all()
    paginator = Paginator(business,100)
    page = request.GET.get('page')

    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page( 1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    index = users.number -1
    max_index = len(paginator.page_range)
    start_index = index -5 if index >= 5 else 0 
    end_index = index + 5 if index <=max_index  -5 else max_index
    page_range = paginator.page_range[start_index:end_index]
    
    query = request.GET.get('q')
    if query:
        products = Product.objects.filter(
            #Q(name__icontains=query)|
            Q(shop_name__icontains=query)
            #Q(description__icontains=query)|
            #Q(created__icontains=query)
        )
        users = User.objects.filter(
            Q(is_shop__icontains=query)
        )
    

    return render (request, 'Profile/shop.html', {'business':business,  'page_range': page_range })

#end view
class Product_detailView(TemplateView):
    template_name = 'shop/detail.html'

    def get(self, request, businessname ,pk=None):

        if pk:
            user = User.objects.get(pk=pk)
            business = get_object_or_404(BusinessAddress, user=user,businessname=businessname,  available=True)
        else:
            user = request.user
            business = get_object_or_404(BusinessAddress, id=id, businessname=businessname, available=True) 

        args = {'business': business, 'user': user}
        
        return render(request,self.template_name, args)

#this is the view for the shop admin
@method_decorator([login_required, client_required], name='dispatch')
class ShopadminView(TemplateView):
    template_name = 'Profile/Shopadmin.html'

    def get(self, request,pk=None):
        
        
        context = {}

        if pk:
           
            user = User.objects.get(pk=pk)
            business = BusinessAddress.objects.filter(user=user).order_by('-date')
            
            
        else:
            
            user = request.user
            business = BusinessAddress.objects.filter(user=request.user.id).order_by('-date')
        args = { 
                 'user' : user,
                  'business' : business,
                 
                 
        }   

        return render(request, self.template_name, args)

#end shopadmin view



#view that creates a shop        
@method_decorator([login_required, client_required], name='dispatch')
class ShopFormView(LoginRequiredMixin, CreateView):
    model = Shop
    form_class = ShopForm
    template_name = 'Profile/shopform.html'
    success_url = reverse_lazy('Profile:Profile')

    def form_valid(self, form):
        shop_name = form.cleaned_data.get('shop_name')
        description = form.cleaned_data.get('description')
        city = form.cleaned_data.get('city')
        website = form.cleaned_data.get('website')
        phone = form.cleaned_data.get('phone')
        image = form.cleaned_data.get('image')
        #user = form.save()
        form.save(self.request.user)

        return super().form_valid(form)


class ShopFormUpdate(UpdateView):
    model = Shop
    form_class = ShopForm
    template_name = 'Profile/editshop.html'
    success_url = reverse_lazy('Profile:Profile')

    def get_object(self):
        try:
            return self.request.user.shop
        except ObjectDoesNotExist:
            print("hello shop")

    def form_valid(self, form):
        shop_name = form.cleaned_data.get('shop_name')
        description = form.cleaned_data.get('description')
        city = form.cleaned_data.get('city')
        website = form.cleaned_data.get('website')
        phone = form.cleaned_data.get('phone')
        image = form.cleaned_data.get('image')
        form.save(self.request.user)
        return super().form_valid(form)


#view that creates a client userprofile
@method_decorator([login_required, client_required], name='dispatch')
class ClientFormView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    template_name = 'Profile/clientform.html'
    success_url = reverse_lazy( 'login:profile')

#    try:
#        form_class = ClientForm
#    except ObjectDoesNotExist:
#        print("hello")
    def form_valid(self, form):
        
        phone = form.cleaned_data.get('phone')
        city = form.cleaned_data.get('city')
        image = form.cleaned_data.get('image')
        gender = form.cleaned_data.get('gender')
        user = form.save()
        form.save(self.request.user)

        return super().form_valid(form)
 

#start client update view
"""This is the view for clients that helps them in updating their profiles   """ 
@method_decorator([login_required, client_required], name='dispatch')
class ClientFormUpdate(UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'Profile/editclient.html'
    success_url = reverse_lazy('login:profile')
    
    def get_object(self):
        try:
            return self.request.user.client
        except ObjectDoesNotExist:
            print ( "hello ")
    
    def form_valid(self, form):
        
        phone = form.cleaned_data.get('phone')
        city = form.cleaned_data.get('city')
        image = form.cleaned_data.get('image')
        gender = form.cleaned_data.get('gender')
        #user = form.save()
        form.save(self.request.user)
        messages.success(self.request, 'The update was done successfully!!!')

        return super().form_valid(form)

#end client update view

login/views/client.py
from django.contrib import messages
from django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator



from login.decorators import client_required
from login.models import  Client, User
from django.views.generic import TemplateView , CreateView
from login.forms import  ClientSignUpForm


class ClientSignUpView(CreateView):
    template_name = 'registration/signup_form.html'
    model = Client
    form_class = ClientSignUpForm

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'client'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('shopp:product_list')

login/views/shop.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator


from login.decorators import client_required, shop_required
from login.models import Shop, User
from django.views.generic import TemplateView , CreateView
from login.forms import ShopSignUpForm


class ShopSignUpView(CreateView):
    template_name = 'registration/signup_form.html'
    model = Shop
    form_class = ShopSignUpForm

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'shop'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('shop:product_list')

Profile/templates/Profile/Shopadmin.html
{% extends "base.html" %}
{% load static %}

{{%  block head %}
<title>Agency Account</title>
{% endblock head  %}}

{% block body %}

<div class="row">
<!-- Fisrt section -->
            <div class="col-12 col-sm-6 col-md-3">
            <br/>
                  <div class="container">
            <div class=" card container shadow-sm  border " style="width: 19rem;"><br>
                <img class="border border-grey"  src="{% if user.shop.image %}
                              {{ user.shop.image.url  }}{% else %}https://images.unsplash.com/photo-1625250564384-a46e5eb9d89c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=529&q=80{% endif  %}
                              " class="img-responsive" style="width:21.2.5rem; height:15rem; " alt="Card image cap">
                
                <div class="card-body">
                  <h5 class="card-title center"> <b>{{ user.shop.shop_name }}</b></h5>
                  
                  <p class="card-text">
              <hr>
                  
                  <p><b>Email </b>  : {{ user.email }}</p>
                  
                  <p><b>City </b>: {{ user.shop.city }}</p>
                  
                  
                
              
        
                  
                </div>
                      
              </div>
                      <div class="container">
                            <br>
                                  <a button type="button" class="btn btn-sm  btn-info btn-block"  href="{% url 'Profile:editshop'  %}"> Edit Your Admin Profile</a></button>  
                                  <a button type="button" class="btn btn-sm  btn-info btn-block"  href="{% url 'shop:businessadress_form'  %}">Post Rental</a></button>  
                      </div> 
            </div> 
            </div>

<!-- second section -->
            <div class="col-12 col-sm-9 col-md-9">
            <br/>
                {% for busines in business %}
                                        
                                <span class="separator">
                                    <div class="row" style="width: 18rem; height:18rem; display:table-row-group;"  >
                                        
                                        <div class="card  border-grey border-top-0 mb-3 shadow-sm " >
                                            <a href="{{ busines.get_absolute_re_path }}">
                                                <img src="{% if busines.image %}{{ busines.image.url }}{% else %}https://images.unsplash.com/photo-1510265236892-329bfd7de7a1?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387{% endif  %}" style="width: 14rem; height:13.5rem;">
                                            </a>
                                            <hr/>
                                            <div class="container">
                                            <a href="{{ busines.get_absolute_re_path }}">{{ busines.businessname }}</a><br/>
                                            {{ busines.county }}
                                             
                                            
                                        </div>
                                            
                                            <div class="container">
                                                {{ busines.building }}
                                            
                                        </div>
                                       
                                        </div>
                                        </div>
                                    </span>  
                                    {% endfor %}      
                           
            </div>




</div>



{% endblock body %}

Profile/templates/Profile/editclient.html
{% extends "base.html" %}  
{% load crispy_forms_tags %}
    { {% block head %}
    <title>Edit </title>
{% endblock head %}}
 {% block body %}
<nav class="navbar navbar-expand text-black shadow navbar " style="background-color:white;">
 edit 
 </nav>
<div class="row">
<div class="col-12 col-sm-6 col-md-3">

</div>

<div class="col-12 col-sm-6 col-md-6">
<br>
<div class="container">
                
               <form method="POST" enctype="multipart/form-data">
                         {% csrf_token %}
                         
                         {{ form|crispy }}
                        <button type="submit" class="btn btn-sm  btn-danger">edit your profile  →</button>
                    </form>
         </div>
</div>

<div class="col-12 col-sm-6 col-md-3">

</div>
</div>










<br/>
<hr/>     
<footer class="container">
      <p class="float-right"><a href="#">Back to top</a></p>
      <p>&copy; Residence &middot; <a href="{% url 'home:privacy' %}">Privacy</a>  <a href="{% url 'home:terms' %}">Terms</a></p>
    </footer>   


 
{% endblock body %}

Profile/templates/Profile/editshop.html
{% extends "base.html" %}  
{% load crispy_forms_tags %}
    { {% block head %}
    <title>Edit </title>
{% endblock head %}}
 {% block body %}
<nav class="navbar navbar-expand text-white shadow navbar " style="background-color:white;">
 edit 
 </nav>
<div class="row">
<div class="col-12 col-sm-6 col-md-3">

</div>

<div class="col-12 col-sm-6 col-md-6">
<br>
<div class="container">
                
               <form method="POST" enctype="multipart/form-data">
                         {% csrf_token %}
                         
                         {{ form|crispy }}
                        <button type="submit" class="btn btn-sm  btn-success">edit Your Residence Profile</button>
                    </form>
         </div>
</div>

<div class="col-12 col-sm-6 col-md-3">

</div>
</div>










<br/>
<hr/>     
<footer class="container">
      <p class="float-right"><a href="#">Back to top</a></p>
      <p>&copy; Realtors and Agents &middot; <a href="{% url 'home:privacy' %}">Privacy</a>  <a href="{% url 'home:terms' %}">Terms</a></p>
    </footer>   


 
{% endblock body %}

Profile/templates/Profile/favourites.html
{% extends "base.html" %}  


{ {% block head %}
    <title>All Agents</title>
{% endblock head %}}

{% block body %}
<nav class="navbar navbar-expand text-black shadow navbar " style="background-color:white;"><b>All Agents</b></nav>
<br/>




    <div class="row no-gutters">
    <!--fist part-->
            <div class="col-12 col-sm-6 col-md-3">

          

            
            </div>
    <!--end fisrt part-->


    <!--second secton-->
        <div class="col-12 col-sm-6 col-md-9" style="color:rgb(21, 20, 13)">



        
       <div class="container"> 
       {% for user in users %}   
       {% if user.is_staff %}   
       {% if user.is_shop %}   
          <div class="">
                
                <div class="mw-100 card">
          
          
          
          <div class="card-body " >
              
                    <div class="row">
                                <div class="col-12 col-md-3">
                                    <a href="{% url 'Profile:view_profile_with_pk' pk=user.pk %}">
                            
                            
                                         <img class="border border-grey rounded" src="{% if user.shop.image %}
                                                     {{ user.shop.image.url  }}{% else %}https://images.unsplash.com/photo-1605475161596-c8ded579e67a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=386&q=80{% endif  %}
                                                    " class="img-responsive" alt="no image" style="width:7.5rem; height:6.5rem;">
                            
                            
                            
                                    </a>
                                </div>
                                <div class="col-12 col-md-3">
                                     
                                    <a href="{% url 'Profile:view_profile_with_pk' pk=user.pk %}">
                                            <b>{{ user.shop.user }}{{ user.shop.shop_name|truncatechars:100 }}</b> 
                                    </a>
                                    </br>
                                    <a >
                                        <b> location: </b>  {{ user.shop.city|truncatechars:100 }}
                                    </a>  
                                   <a>
                                            <p><b>contacts:</b> {{ user.shop.phone|truncatechars:100 }}</p>
                                    </a>  
                                        

                                </div>
                                <div class="col-12 col-md-6">
                                <h6 style="color:teal;"><b>Description</b></h6>
                                       <p style="color:black;">{{ user.shop.description|truncatechars:100 }}</p>

                                        {% if not user in friends %}
                    
                    {% endif %}
     

                                </div>
                    </div>


               
           
        
          
         </div>
         
</div>

         
        </div>
        {% else %}


 


        {% endif %}
       {% endif %}
 {% endfor %}






      </div>

 


<!--end second section-->


    <br/>

{% include "paginationn.html" %} 

    </div>
    
      <hr/>
     
     
      <footer class="container">
            <p class="float-right"><a href="#">Back to top</a></p>
              
            <p>Realtors and Agents &copy; 2022 <a href="{% url 'home:privacy' %}">Privacy</a> Favourite Devs <a href="#">Terms</a></p>
          </footer>   
    

{% endblock body %}

Profile/templates/Profile/product_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{{%  block head %}
<title>add_new_product</title>
{% endblock head  %}}

{% block body %}

<nav class="navbar navbar-expand text-white shadow navbar " style="background-color:teal;">Add Product</nav>
<br/>

<div class="">
<div class="col-12 col-sm-6 col-md-3">

</div>


        <div class="col-12 col-sm-6 col-md-6">
           <div class="container">
                
               <form method="POST" enctype="multipart/form-data">
                         {% csrf_token %}
                         
                         {{ form|crispy }}
                        <button type="submit" class="btn btn-sm  btn-success">add product</button>
                    </form>
         </div>
        </div>     
        
    </div>
</div> 
</div>
        <!--section 2-->
    <div class="col-12 col-sm-6 col-md-3" >
    
    
    
    
        
            
    </div>







</div>

<br/>
<hr/>     
<footer class="container">
      <p class="float-right"><a href="#">Back to top</a></p>
      <p>&copy; Favourite.inc &middot; <a href="{% url 'home:privacy' %}">Privacy</a> Favourite <a href="#">Terms</a></p>
    </footer>   


{% endblock %}

Profile/templates/Profile/shop.html
{% extends "base.html" %} 
{% load crispy_forms_tags %} 
{ {% block head %}
    <title>Estates and Realtors</title>
{% endblock head %}}

{% block body %}


<br/>




    <div class="container">
    {% for busines in business %}
                                        
                                <span class="separator">
                                    <div class="row" style="width: 18rem; height:18rem; display:table-row-group;"  >
                                        
                                        <div class="card  border-grey border-top-0 mb-3 shadow-sm " >
                                            <a href="{{ busines.get_absolute_re_path }}">
                                                <img src="{% if busines.image %}{{ busines.image }}{% else %}https://images.unsplash.com/photo-1510265236892-329bfd7de7a1?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387{% endif  %}" style="width: 14rem; height:13.5rem;">
                                            </a>
                                            <hr/>
                                            <div class="container">
                                            <a href="">{{ busines.businessname }}</a><br/>
                                            {{ busines.county }}
                                              B000{{ busines.uniqueadress }}  
                                            
                                        </div>
                                            
                                            <div class="container">
                                                {{ busines.building }}
                                            
                                        </div>
                                      
                                        <div class="container"><a href="/home/map/"><b>show on map</b></a>

                                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                                    class="bi bi-share" viewBox="0 0 16 16">
                                                        <path d="M13.5 1a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM11 2.5a2.5 2.5 0 1 1 .603 1.628l-6.718 3.12a2.499 2.499 0 0 1 0 1.504l6.718 3.12a2.5 2.5 0 1 1-.488.876l-6.718-3.12a2.5 2.5 0 1 1 0-3.256l6.718-3.12A2.5 2.5 0 0 1 11 2.5zm-8.5 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm11 5.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3z"/>
                                                        </svg>
                                            
                                        <br/></div>
                                        
                                        </div>
                                        </div>
                                    </span>  
                                    {% endfor %}      
                           

                </div>





{% include "paginationn.html" %} 

      <hr/>
     
     
      <footer class="container">
            <p class="float-right"><a href="#">Back to top</a></p>
              
            <p> &copy; 2022 <a href="{% url 'home:privacy' %}">Privacy</a> Residence Technology <a href="#">Terms</a></p>
          </footer>   
    
   
    

{% endblock body %}