Profile/urls.py
from django.urls import include, re_path
from Profile.views import ProfileView  ,ShopadminView , shop, favouriteshops,AboutView 
from .import views
from .views import  ShopFormView  , ClientFormUpdate ,ClientFormView, ShopFormUpdate

from shopp.views import delete_view, Resident_detailView
app_name='Profile'

urlpatterns = [
    re_path(r'^Profile/$', ProfileView.as_view(), name='Profile'),
    re_path(r'^Profile/(?P<pk>\d+)/$', ProfileView.as_view(), name='view_profile_with_pk'),
    re_path(r'^editclient/$', ClientFormUpdate.as_view(), name='editclient'),
    re_path(r'^Shopadmin/$', ShopadminView.as_view(), name='Shopadmin'),
    re_path(r'^shop/$', views.shop, name='shop'),
    re_path(r'^favouriteshops/$', views.favouriteshops, name='favouriteshops'),
    re_path(r'^about', AboutView.as_view(), name='about'),
    re_path(r'^(?P<uniqueadress>\d+)/(?P<date>[-\w]+)/$', Resident_detailView.as_view(), name='detail'),
    #re_path(r'^Profile/(?P<id>\d+)/(?P<slug>[-\w]+)/$', ProfileView.as_view(), name='user_post_detail'),
    #re_path('product_form/', ProductFormView.as_view(), name = 'product_form'),
    re_path('shopform/', ShopFormView.as_view(), name='Shopform'),
    re_path('clientform/', ClientFormView.as_view(), name='Clientform'),
    re_path(r'^editshop/$', ShopFormUpdate.as_view(), name = 'editshop' )
    
]

estate/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include ,path ,re_path


from login.views import  client , shop, login

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('home/',include('home.urls',namespace='home')),
    #path('main/',include('main.urls',namespace='main')),
    re_path(r'', include('shopp.urls',namespace='shop')),
    path('', include('login.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', login.SignUpView.as_view(), name='signup'),
    path('accounts/signup/client/', client.ClientSignUpView.as_view(), name='client_signup'),
    path('accounts/signup/shop/', shop.ShopSignUpView.as_view(), name='shop_signup'),
    #path('shopp/',include('shopp.urls',namespace='shop')),
    path('Profile/',include('Profile.urls',namespace='Profile')),
    
    
]
   
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   

home/urls.py
from django.conf.urls import url
from django.urls import include, re_path
#from home.views import 
from django.contrib.auth import views as auth_views
from . import views as myapp_views
from home import views
from . import views 
from home.views import ContactView, PrivacyView, TermsView, MarkersMapView, AboutView, HomeView, coordinates_form, maps #, map, route


app_name = 'home'


urlpatterns = [
    re_path(r'^$', HomeView.as_view(), name='home'),
    re_path(r'^privacy/', PrivacyView.as_view(), name='privacy' ),
    re_path(r'^terms/', TermsView.as_view(), name='terms'),
    #re_path(r"^map/", MarkersMapView.as_view(),name="map"),
    #re_path(r'^route/', views.route, name="route"),
    re_path(r'^coordinates-form/',views.coordinates_form, name = 'coordinates-form'),
    re_path(r'^map/', views.maps, name="map"),
    
    re_path(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$', 
            views.change_friends, name='change_friends'),
    re_path('contact/', ContactView.as_view(), name='Contact'),
    re_path(r'^about/', AboutView.as_view(), name='about'),

  
]

login/urls.py
from django.urls import include, path
from .views import login, client, shop
from django.conf import settings
from django.conf.urls import url
from django.urls import include, re_path
from django.urls import include ,path
from django.contrib.auth import (
    login,
    logout,
#     password_reset_confirm,
#      password_reset,
#     password_reset_done,
#     password_reset_complete
     )
from django.contrib.auth.views import(
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from . import views as myapp_views
from . import views
from  .views import login 

app_name = 'login'

urlpatterns = [

    path('clients/', include(([
        re_path(r'^profile/$',login.ProfileView.as_view(), name='profile'),
        re_path(r'^profile/edit/$', login.edit_profile, name='edit_profile'),
        re_path(r'^change-password/$', login.change_password, name='change_password'),
        #re_path(r'^reset-password/$', password_reset,{ 'template_name':
        #          'login/reset_password.html','post_reset_redirect':
        #          'login:password_reset_done','email_template_name':
        #          'login:reset_password_email.html' }, name='reset_password'),
        #re_path(r'^reset-password/done/$', password_reset_done, 
        #          {'template_name':'login/reset_password_done.html'},
        #          name='password_reset_done'),
        #re_path(r'^reset-password/confirm/$', password_reset_confirm, name='password_reset_confirm'),

        #re_path(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        #          password_reset_confirm, {'template_name':
        #          'login/reset_password_confirm.html', 'post_reset_redirect':
        #          'login:password_reset_complete'},  name='password_reset_confirm'),

        #re_path(r'^reset-password/complete/$', password_reset_complete,{'template_name':
        #          'login/reset_password_complete.html'}, name='password_reset_complete'),
        re_path(r'^logout/$', logout, name='logout'),
#accounts/logout/ [name='logout']
        re_path(r'^about/$', login.about, name='about'),
        #re_path(r'^delete/(?P<username>[\w|\W.-]+)/$', views.delete_user, name='delete-user')

    ]))),


    path('shops/', include(([
        #re_path(r'^profile/$',login.ProfileView.as_view(), name='profile'),
        re_path(r'^profile/edit/$', login.edit_profile, name='edit_profile'),
        re_path(r'^change-password/$', login.change_password, name='change_password'),
        
     
        #re_path(r'^logout/$', logout, name='logout'),
        re_path(r'^logout/$', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),

        re_path(r'^about/$', login.about, name='about')

    ])))
 
]





    

Profile/views.py
from django.views.generic import TemplateView
from django.http import Http404
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from login.models import User, Client, Shop
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.views.generic import (ListView, UpdateView, CreateView, FormView, DeleteView)
from django.utils.decorators import method_decorator
from shopp.models import Shop
from django.core.paginator import Paginator
from Profile.models import About
from types import MethodType
from operator import attrgetter
#from shopp.forms import ProductForm
from Profile.forms import ShopForm, ClientForm
from login.decorators import shop_required, client_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from home.models import Friend
from django.urls import reverse_lazy 
from random import randint
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from shopp.models import BusinessAddress

#this is the view that helps users to view shops either theirs or others!!! it has pk that diffrentiates between the two
class ProfileView(TemplateView):
    template_name = 'Profile/Profile.html'
    
    def get(self, request, category_slug=None, pk=None):
        category = None
        context = {}

        if pk:
           
            user = User.objects.get(pk=pk)
            business = BusinessAddress.objects.filter(user=user).order_by('-date')
            print(business)
            
        else:
            category = None
            user = request.user
            business = BusinessAddress.objects.filter(user=request.user.id).order_by('-date')
            print(business)
        args = { 
                 'user' : user,
                  'business' : business,
                 
                 
        }   
          


       
        

   
       
        return render(request, self.template_name, args)

#end view 

#about view
class AboutView(TemplateView):
    template_name = 'Profile/about.html'

    def get(self, request):
        about = About.objects.all()
        
        args = {'about': about}
        return render(request, self.template_name, args)

#end about
 
#view that shows favourite shops
def favouriteshops(request):

    try:
        #users = User.objects.exclude(id=request.user.id)
        users = User.objects.all()
        friend = Friend.objects.get(current_user=request.user)
        friends = friend.users.all()
    except:
        users = User.objects.all()
        friends = print("no favourites!!!")

    return render (request, 'Profile/favourites.html', {'users':users,'friends': friends  })

#end view

#view that shows all  shops, this view was originally a class but changed to accomodate pagination which later should be returned to a class
#@login_required
def shop(request, category_slug=None):

    business = BusinessAddress.objects.all()
    paginator = Paginator(business,100)
    page = request.GET.get('page')

    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page( 1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    index = users.number -1
    max_index = len(paginator.page_range)
    start_index = index -5 if index >= 5 else 0 
    end_index = index + 5 if index <=max_index  -5 else max_index
    page_range = paginator.page_range[start_index:end_index]
    
    query = request.GET.get('q')
    if query:
        products = Product.objects.filter(
            #Q(name__icontains=query)|
            Q(shop_name__icontains=query)
            #Q(description__icontains=query)|
            #Q(created__icontains=query)
        )
        users = User.objects.filter(
            Q(is_shop__icontains=query)
        )
    

    return render (request, 'Profile/shop.html', {'business':business,  'page_range': page_range })

#end view
class Product_detailView(TemplateView):
    template_name = 'shop/detail.html'

    def get(self, request, businessname ,pk=None):

        if pk:
            user = User.objects.get(pk=pk)
            business = get_object_or_404(BusinessAddress, user=user,businessname=businessname,  available=True)
        else:
            user = request.user
            business = get_object_or_404(BusinessAddress, id=id, businessname=businessname, available=True) 

        args = {'business': business, 'user': user}
        
        return render(request,self.template_name, args)

#this is the view for the shop admin
@method_decorator([login_required, client_required], name='dispatch')
class ShopadminView(TemplateView):
    template_name = 'Profile/Shopadmin.html'

    def get(self, request,pk=None):
        
        
        context = {}

        if pk:
           
            user = User.objects.get(pk=pk)
            business = BusinessAddress.objects.filter(user=user).order_by('-date')
            
            
        else:
            
            user = request.user
            business = BusinessAddress.objects.filter(user=request.user.id).order_by('-date')
        args = { 
                 'user' : user,
                  'business' : business,
                 
                 
        }   

        return render(request, self.template_name, args)

#end shopadmin view



#view that creates a shop        
@method_decorator([login_required, client_required], name='dispatch')
class ShopFormView(LoginRequiredMixin, CreateView):
    model = Shop
    form_class = ShopForm
    template_name = 'Profile/shopform.html'
    success_url = reverse_lazy('Profile:Profile')

    def form_valid(self, form):
        shop_name = form.cleaned_data.get('shop_name')
        description = form.cleaned_data.get('description')
        city = form.cleaned_data.get('city')
        website = form.cleaned_data.get('website')
        phone = form.cleaned_data.get('phone')
        image = form.cleaned_data.get('image')
        #user = form.save()
        form.save(self.request.user)

        return super().form_valid(form)


class ShopFormUpdate(UpdateView):
    model = Shop
    form_class = ShopForm
    template_name = 'Profile/editshop.html'
    success_url = reverse_lazy('Profile:Profile')

    def get_object(self):
        try:
            return self.request.user.shop
        except ObjectDoesNotExist:
            print("hello shop")

    def form_valid(self, form):
        shop_name = form.cleaned_data.get('shop_name')
        description = form.cleaned_data.get('description')
        city = form.cleaned_data.get('city')
        website = form.cleaned_data.get('website')
        phone = form.cleaned_data.get('phone')
        image = form.cleaned_data.get('image')
        form.save(self.request.user)
        return super().form_valid(form)


#view that creates a client userprofile
@method_decorator([login_required, client_required], name='dispatch')
class ClientFormView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    template_name = 'Profile/clientform.html'
    success_url = reverse_lazy( 'login:profile')

#    try:
#        form_class = ClientForm
#    except ObjectDoesNotExist:
#        print("hello")
    def form_valid(self, form):
        
        phone = form.cleaned_data.get('phone')
        city = form.cleaned_data.get('city')
        image = form.cleaned_data.get('image')
        gender = form.cleaned_data.get('gender')
        user = form.save()
        form.save(self.request.user)

        return super().form_valid(form)
 

#start client update view
"""This is the view for clients that helps them in updating their profiles   """ 
@method_decorator([login_required, client_required], name='dispatch')
class ClientFormUpdate(UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'Profile/editclient.html'
    success_url = reverse_lazy('login:profile')
    
    def get_object(self):
        try:
            return self.request.user.client
        except ObjectDoesNotExist:
            print ( "hello ")
    
    def form_valid(self, form):
        
        phone = form.cleaned_data.get('phone')
        city = form.cleaned_data.get('city')
        image = form.cleaned_data.get('image')
        gender = form.cleaned_data.get('gender')
        #user = form.save()
        form.save(self.request.user)
        messages.success(self.request, 'The update was done successfully!!!')

        return super().form_valid(form)

#end client update view

login/views/client.py
from django.contrib import messages
from django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator



from login.decorators import client_required
from login.models import  Client, User
from django.views.generic import TemplateView , CreateView
from login.forms import  ClientSignUpForm


class ClientSignUpView(CreateView):
    template_name = 'registration/signup_form.html'
    model = Client
    form_class = ClientSignUpForm

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'client'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('shopp:product_list')

login/views/shop.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator


from login.decorators import client_required, shop_required
from login.models import Shop, User
from django.views.generic import TemplateView , CreateView
from login.forms import ShopSignUpForm


class ShopSignUpView(CreateView):
    template_name = 'registration/signup_form.html'
    model = Shop
    form_class = ShopSignUpForm

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'shop'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('shop:product_list')

login/templates/login/about.html
{% extends "base.html" %}


{{%  block head %}
<title>about</title>
{% endblock head  %}}

{% block body %}
<nav class="navbar navbar-expand text-white shadow navbar " style="background-color:teal;">about favourite</nav>
<div class="jumbotron">
     <h6>favourite is a plartform created to and for easy and quality shopping.There are a no of shops in the site and many more will be available in the
     coming months.We expect to enroll more than a hundred shops by the end of the year.Upon login a user is able to access a viriety of products and shops offering those products in nairobi.
      The user also enjoy the privilede of adding shops to his/her favourite list for asier access and update of shops. Shops on the plartform also enjoy 
      the priledge of updating their clients on new products that they have bo=rought in the market and thi will result in increased sales. We urge all shops to strictly adher to 
      favourite's terms and conditions' 
     </h6>

</div>


{% endblock body %} 

login/templates/login/accounts.html
 {% extends "base.html" %}   
    
 {% load crispy_forms_tags %}

 {{%  block head %}
<title>Login to Favourite</title>
{% endblock head  %}}

{% block body %}

<br/>

<div class="container">
<div class="row">
    <div class="col-3 col-md col-md-3">
        <div class="container">
          <h4></h4>
        </div>
            
        </div>

            <!--section 2-->
        <div class="col-12 col-sm-6 col-md-6" >
            
           <h2>Login</h2><b>
           <form method="POST">
              {% csrf_token %}   
              {{ form|crispy }}
              <button type="submit" class="btn btn-primary" name="button">Sign In</button>          
           </form>
        </b>
        <br/>
        <a href="{% url 'login:reset_password'  %}"><h5>Forgot password?</h5> </a>
        <a  href="{% url 'login:register'  %}"> <h5> Sign Up</h5></a>
        
           </div>

            </div>

            <div class="col-3 col-md col-md-3">
                <div class="container" style="color:olive;"><h4></h4>
              
                  </div>
                </div>
        



<br>
<hr/>
<footer class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>&copy; Resident &middot; <a href="{% url 'home:privacy' %}">Privacy</a>Resident <a href="{% url 'home:terms' %}">Terms</a></p>
</footer> 


<!--<div class="rights">
    <h6 class="container">2022 © Favourite</h6>
</div>
</div>-->
{% endblock body %}

login/templates/login/edit_profile.html
{% extends "base.html" %}  
{% load crispy_forms_tags %}
    { {% block head %}
    <title>Profile</title>
{% endblock head %}}
 {% block body %}

 

 <br />


<!--dividing into 3 columns-->
<div class="row">
    <!--first column-->
    <div class="col-md-3"></div>
    <!--end fisrt column-->
    <!--second column-->
    <div class="col-md-6">
            <div class="" role="alert"><p>Want to edit your profile?? You can edit your profile here!!!</p></div>
                       <form method="POST">
                           {% csrf_token %} 
                           {{ form|crispy }}
                           <br />
                           <button type="submit" class="btn btn-danger outline">Submit</button>
                       </form>
            </div>              
    </div>
    <!--end second column-->
    <!--third column-->
    <div class="col-md-3"></div>
    <!--end third column-->
</div>
<br/>
<hr/>
<!--Footer-->
<footer class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy;  &middot; <a href="#">Privacy</a> Resident <a href="#">Terms</a></p>
</footer> 
<!--end footer-->
{% endblock body %} 

login/templates/login/logout.html
{% extends "base.html" %} 

{{%  block head %}
<title>You have logged out</title>
{% endblock head  %}}
{% block body %}


</div>
<div class="container">
    <div class="col-sm-6 col-sm-offset-3">
<br/>
<p class="alert alert-danger" role="alert">
    you have logged out successfully !!!!
</p>
   
   <a href="{ % url 'login:login' %}"  type="button" class="btn btn-outline-success" role="button">login again</a>   
    
</form>
</div>
</div>
{% endblock body %}
 

login/templates/login/profile.html
{% extends "base.html" %}

    { {% block head %}
    <title>Profile</title>
{% endblock head %}}
 {% block body %} 
<!--navbar with profile element tabs user authentication is necessary for security-->
 
<nav class="navbar navbar-expand text-white shadow navbar " style="background-color:white;">
    {% if user.is_authenticated %}
    <div class="dropdown">
        <button class="btn btn-sm  dropdown-toggle text-red" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color:white;">
         Edit profile
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
        
         <!-- <a class="nav-item nav-link dropdown-item " href="{% url 'Profile:Clientform'  %}">create Profile</a>-->
          
          <a class="nav-item nav-link dropdown-item " href="{% url 'Profile:editclient' %}">profile</a>
      
          
          <a class="nav-item nav-link dropdown-item " href="{% url 'login:edit_profile'  %}">Edit Profile</a>
          <a class="nav-item nav-link dropdown-item " href="{% url 'login:change_password'  %}">Change Password</a>
          <a class="nav-item nav-link dropdown-item " href="{% url 'login:logout' %}">Logout</a>
        </div>
      </div>
      {% endif %}

</nav>
   

<br/>




    <div class="row no-gutters">
        <div class="col-12 col-sm-6 col-md-3">

          <div class="container">
            <div class=" mw-100 p-2 card  border-0 " style="width: 21.5rem;">
             

                 <img class="card-img-top" src=" {% if user.client.image %}{{ user.client.image.url  }}
                 {% else %}https://cdn.pixabay.com/photo/2018/03/30/15/11/deer-3275594_960_720.jpg{% endif  %}"
                  style="width:21.2.5rem; height:15rem; " alt="Card image cap">
                <div class="card-body">
                  <h5 class="card-title center"> <b>{{ user }}</b></h5>
                  <p class="card-text font-italic " style="color:red;"><p>{{ user.client.description }}</p></p>
                  <p class="card-text">
              <hr>
                  
                  <p><b>Email </b>  : {{ user.email }}</p>
                  
                  <p><b>City </b>: {{ user.client.county }}</p>
                  <p><b>Contacts</b>: {{ user.client.phone }}</p>
              
        
                  
                </div>
              </div>
            </div>


            
          </div>

        <div class="col-12 col-sm-6 col-md-6" style="color:rgb(21, 20, 13)">


       <div class="container"> 
       
       <div class=" row"   >
           {% for resident in resident %}
                                        
                                <span class="separator">
                                    <div class="row" style="width: 18rem; height:18rem; display:table-row-group;"  >
                                        
                                        <div class="card  border-grey border-top-0 mb-3 shadow-sm " >
                                            <a href="{{ resident.get_absolute_re_path }}">
                                                <img src="{% if resident.image %}{{ resident.image.url }}{% else %}https://images.unsplash.com/photo-1510265236892-329bfd7de7a1?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387{% endif  %}" style="width: 14rem; height:13.5rem;">
                                            </a>
                                            <hr/>
                                            <div class="container">
                                            <a href="">{{ resident.building }}</a><br/>
                                            {{ resident.county }}
                                              R000{{ resident.uniqueadress }}  
                                            
                                        </div>
                                            
                                            <div class="container">
                                                {{ resident.building }}
                                            
                                        </div>
                                        <div class="container"><a href="/home/map/"><b>show on map</b></a><br/></div>
                                        
                                        </div>
                                        </div>
                                    </span>  
                                    {% endfor %}      
      </div>
  </div>
</div>



<div class="col-12 col-sm-6 col-md-3">

       

</div>


      












</div>
<br>
<hr>
<footer class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>&copy; Favourite &middot; <a href="{% url 'home:privacy' %}">Privacy</a> Resident <a href="{% url 'home:terms' %}">Terms</a></p>
  </footer> 


{% endblock body %} 

login/templates/login/reg_form.html
{% extends "base.html" %} 
{% load crispy_forms_tags %} 

{{%  block head %}
<title>Signup</title>
{% endblock head  %}}
    
        {% block body %}
       <h5>Welcome Create an account here!</h5>
    <div class="Loginbox">
            <div class="container-fluid">

</div>
    

    <div class="row">
        <div class="col-3 col-md col-md-3">
            <div class="container">
                <h4>   Already have an account ?? then</h4> 
              <a href="{% url 'login:login'  %}" class="btn btn-sm btn-primary"><button type="button" class="btn btn-primary btn-sm">Sign In</button></a>
            </div>
                
            </div>
    
                <!--section 2-->
            <div class="col-12 col-sm-6 col-md-6" style="color:rgb(9, 109, 92);">
                    
                <b>
                <div class="container"> 
                    <form method="POST">
                         {% csrf_token %}
                         {{ form|crispy }}
                        <button type="submit" class="btn btn-success">Sign up</button>
                    </form>
                </div></b>
                </div>
                
    
    
                </div>
            
                    
                </div>
               
    
                <div class="col-3 col-md col-md-3">
                    <div class="container" style="color:olive;"><h4></h4>
    
    
                        
        
                        
              
                  
                      </div>
                    </div>
            
          

    
    <br/>
      <footer class="container">
            <p class="float-right"><a href="#">Back to top</a></p>
            <p>&copy; Resident Tech &middot; <a href="#">Privacy</a>  <a href="#">Terms</a></p>
          </footer>
        {% endblock body %}
    

login/templates/login/reset_password.html
{% extends "base.html" %}  
{% load crispy_forms_tags %} 

{{%  block head %}
<title>Reset password</title>
{% endblock head  %}}    
{% block body %}


<br/>
<div class="container">
    <div class="col-sm-6 col-sm-offset-3">
        
        <div class="alert alert-warning" role="alert">
            <p>
                Forgotten your password? Enter your email address below, and well email instructions for setting a new one
            </p>
          </div>         

<h2>Reset password</h2>
<br/>
<form method="POST">
   {% csrf_token %}   
   {{form|crispy }}
   <button type="submit" class="btn btn-danger" name="button">reset password</button>
</form>
</div>
</div>
{% endblock body %}

login/templates/login/reset_password_complete.html
{% extends "base.html" %}  

{{%  block head %}
<title>Reset password complete</title>
{% endblock head  %}}

{% block body %}

<nav class="navbar navbar-expand text-white shadow-sm navbar " style="background-color:white;"><h6> password reset complete!!</h6></nav>
<div class="container">
    <div class="col-sm-6 col-sm-offset-3">
         
<br/>
<h2>Password reset complete</h2>
<p class="lead">Your password reset is complete. You can proceed to login with your new password.
    
</p>
 

<a href="{% url 'login'  %}" class="btn btn-success" role="button">login again</a>

</div>

</div>

{% endblock body %}

login/templates/login/reset_password_confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags %} 

{{%  block head %}
<title>Reset password confirm</title>
{% endblock head  %}}
{% block body %}
<nav class="navbar navbar-expand text-white shadow navbar " style="background-color:white;"><h5>Welcome to reset your password</h6></div></nav>

<br>
<div class="container">
    <div class="col-sm-6 col-sm-offset-3">
        
        <div class="alert alert-warning" role="alert">
            <p>
                Forgotten your password? 
            </p>
          </div>         

<h2>Enter New password</h2>
<br/>
<form method="POST">
   {% csrf_token %}   
   {{form|crispy }}
   <button type="submit" class="btn btn-danger" name="button">reset password</button>
</form>
</div>
</div>
{% endblock body %}

login/templates/login/reset_password_done.html
{% extends "base.html" %}   
{% load crispy_forms_tags %}
    { {% block head %}
    <title>reset password sent to your email</title>
{% endblock head %}}   
{% block body %}

<nav class="navbar navbar-expand text-white shadow navbar " style="background-color:white;"><h6>Reset password sent !!</h6></nav>
<div class="container">
    <div class="">
         
<br/>
<h2>Reset password link sent. </h2>

 <p class="lead">
    We've emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.
  </p>
  <p class="lead">
    If you don't receive an email, please <b>make sure you've entered the address you registered with</b>,
    and check your spam folder.
  </p>

</div>
</div>
{% endblock body %}

login/templates/login/reset_password_email.html
{% autoescape off %}

  
 To initiate the password reset process for your {{ user.get_username }} Resident Account,
click the link below:


{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'login:password_reset_confirm' uidb64=uid token=token  %}
{% endblock reset_link %}


If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The Resident Team
{% endautoescape %}