Profile/urls.py
from django.urls import include, re_path
from Profile.views import ProfileView  ,ShopadminView , shop, favouriteshops,AboutView 
from .import views
from .views import  ShopFormView  , ClientFormUpdate ,ClientFormView, ShopFormUpdate

from shopp.views import delete_view, Resident_detailView
app_name='Profile'

urlpatterns = [
    re_path(r'^Profile/$', ProfileView.as_view(), name='Profile'),
    re_path(r'^Profile/(?P<pk>\d+)/$', ProfileView.as_view(), name='view_profile_with_pk'),
    re_path(r'^editclient/$', ClientFormUpdate.as_view(), name='editclient'),
    re_path(r'^Shopadmin/$', ShopadminView.as_view(), name='Shopadmin'),
    re_path(r'^shop/$', views.shop, name='shop'),
    re_path(r'^favouriteshops/$', views.favouriteshops, name='favouriteshops'),
    re_path(r'^about', AboutView.as_view(), name='about'),
    re_path(r'^(?P<uniqueadress>\d+)/(?P<date>[-\w]+)/$', Resident_detailView.as_view(), name='detail'),
    #re_path(r'^Profile/(?P<id>\d+)/(?P<slug>[-\w]+)/$', ProfileView.as_view(), name='user_post_detail'),
    #re_path('product_form/', ProductFormView.as_view(), name = 'product_form'),
    re_path('shopform/', ShopFormView.as_view(), name='Shopform'),
    re_path('clientform/', ClientFormView.as_view(), name='Clientform'),
    re_path(r'^editshop/$', ShopFormUpdate.as_view(), name = 'editshop' )
    
]

estate/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include ,path ,re_path


from login.views import  client , shop, login

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('home/',include('home.urls',namespace='home')),
    #path('main/',include('main.urls',namespace='main')),
    re_path(r'', include('shopp.urls',namespace='shop')),
    path('', include('login.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', login.SignUpView.as_view(), name='signup'),
    path('accounts/signup/client/', client.ClientSignUpView.as_view(), name='client_signup'),
    path('accounts/signup/shop/', shop.ShopSignUpView.as_view(), name='shop_signup'),
    #path('shopp/',include('shopp.urls',namespace='shop')),
    path('Profile/',include('Profile.urls',namespace='Profile')),
    
    
]
   
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   

home/urls.py
from django.conf.urls import url
from django.urls import include, re_path
#from home.views import 
from django.contrib.auth import views as auth_views
from . import views as myapp_views
from home import views
from . import views 
from home.views import ContactView, PrivacyView, TermsView, MarkersMapView, AboutView, HomeView, coordinates_form, maps #, map, route


app_name = 'home'


urlpatterns = [
    re_path(r'^$', HomeView.as_view(), name='home'),
    re_path(r'^privacy/', PrivacyView.as_view(), name='privacy' ),
    re_path(r'^terms/', TermsView.as_view(), name='terms'),
    #re_path(r"^map/", MarkersMapView.as_view(),name="map"),
    #re_path(r'^route/', views.route, name="route"),
    re_path(r'^coordinates-form/',views.coordinates_form, name = 'coordinates-form'),
    re_path(r'^map/', views.maps, name="map"),
    
    re_path(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$', 
            views.change_friends, name='change_friends'),
    re_path('contact/', ContactView.as_view(), name='Contact'),
    re_path(r'^about/', AboutView.as_view(), name='about'),

  
]

login/urls.py
from django.urls import include, path
from .views import login, client, shop
from django.conf import settings
from django.conf.urls import url
from django.urls import include, re_path
from django.urls import include ,path
from django.contrib.auth import (
    login,
    logout,
#     password_reset_confirm,
#      password_reset,
#     password_reset_done,
#     password_reset_complete
     )
from django.contrib.auth.views import(
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from . import views as myapp_views
from . import views
from  .views import login 

app_name = 'login'

urlpatterns = [

    path('clients/', include(([
        re_path(r'^profile/$',login.ProfileView.as_view(), name='profile'),
        re_path(r'^profile/edit/$', login.edit_profile, name='edit_profile'),
        re_path(r'^change-password/$', login.change_password, name='change_password'),
        #re_path(r'^reset-password/$', password_reset,{ 'template_name':
        #          'login/reset_password.html','post_reset_redirect':
        #          'login:password_reset_done','email_template_name':
        #          'login:reset_password_email.html' }, name='reset_password'),
        #re_path(r'^reset-password/done/$', password_reset_done, 
        #          {'template_name':'login/reset_password_done.html'},
        #          name='password_reset_done'),
        #re_path(r'^reset-password/confirm/$', password_reset_confirm, name='password_reset_confirm'),

        #re_path(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        #          password_reset_confirm, {'template_name':
        #          'login/reset_password_confirm.html', 'post_reset_redirect':
        #          'login:password_reset_complete'},  name='password_reset_confirm'),

        #re_path(r'^reset-password/complete/$', password_reset_complete,{'template_name':
        #          'login/reset_password_complete.html'}, name='password_reset_complete'),
        re_path(r'^logout/$', logout, name='logout'),
#accounts/logout/ [name='logout']
        re_path(r'^about/$', login.about, name='about'),
        #re_path(r'^delete/(?P<username>[\w|\W.-]+)/$', views.delete_user, name='delete-user')

    ]))),


    path('shops/', include(([
        #re_path(r'^profile/$',login.ProfileView.as_view(), name='profile'),
        re_path(r'^profile/edit/$', login.edit_profile, name='edit_profile'),
        re_path(r'^change-password/$', login.change_password, name='change_password'),
        
     
        #re_path(r'^logout/$', logout, name='logout'),
        re_path(r'^logout/$', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),

        re_path(r'^about/$', login.about, name='about')

    ])))
 
]





    

shopp/urls.py
from django.conf.urls import include, re_path
from .import views
from .views import  AbouttView,  all_shops
from shopp.views import Product_detailView, ShopsView, delete_view, product_delete_view, BusinessAdressFormView,Product_detailView,ResidentAddressFormView
#from Profile.views import ProductDeleteView


app_name = 'shopp'

urlpatterns = [
    re_path(r'^$', views.product_list, name='product_list'),
    #re_path(r'^(?P<id>\d+)/delete/', views.product_list, name='product_list'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    re_path('^<int:id>/delete/$', product_delete_view, name='product_delete'),
    re_path(r'^$', ShopsView.as_view(), name='shops'),
    re_path('shopp/businessadress_form/', BusinessAdressFormView.as_view(), name='businessadress_form'),
    re_path('shopp/residentadressform/', ResidentAddressFormView.as_view(), name='residentadressform'),
    re_path(r'^(?P<uniqueadress>\d+)/(?P<slug>[-\w]+)/$', Product_detailView.as_view(), name='business_detail'),
    #re_path(r'^(?P<pk>\d+)/(?P<slug>[-\w]+)/$', Product_detailView.as_view(), name='business_detail_with_pk'),
    re_path(r'^about_uss/$',views.AbouttView, name='about_uss'),
    re_path(r'^contact_us/$', views.contact_us , name='contact_us'),
    re_path(r'^registershop/$', views.registershop, name='registershop'), 
    
    re_path(r'^search/$', views.search, name='search'),  
    re_path(r'^all_shops/$', views.all_shops, name='all_shops'),
    #re_path(r'^<int:product_pk>/(?P<slug>[-\w]+)/delete/',ProductDeleteView.as_view(), name='product_delete'),
    

    
]

home/forms.py
from django import forms
from home.models import Contact,Newsletter
from django.forms import ModelForm

from .models import *

class CoordinatesForm(forms.ModelForm):
    lat = models.CharField(max_length=20)
    lon = models.CharField(max_length=20)

class Meta:
    model = Coordenadas
    fields = '__all__'

class ContactForm(forms.ModelForm):
    phone  = forms.DecimalField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Write your phone number here...'
        }
    ))
    class Meta:
        model = Contact

        fields = [
            'name',
            'email',
            'content'
            
        ]


class NewsletterForm(forms.ModelForm):

    attrs={
        'class':'form-control',
        'placeholder': 'Write your email here...'
    }
    class Meta:
        model = Newsletter
        fields = [
            'email'
       ]

home/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404
#from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from login.models import User
#from home.forms import HomeForm, HomeCreate
#from home.models import Post, Friend
#from .models import Create
from home.forms import ContactForm, NewsletterForm
from home.models import Contact, Privacy, Terms, Aboutpage
from login.models import Client, Shop
from .models import Friend, Post, Newsletter
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView # new
from django.urls import reverse_lazy
from random import randint
from home.models import Post, Homepage, Aboutpage
from django.shortcuts import render, redirect, reverse
from django.conf import settings
from shopp.models import BusinessAddress
#from geopy.geocoders import Nominatim
import folium
import pandas as pd
#from folium import plugins
#gee
#import ee
#service_account = ' residentgeolocate@resident-350617.iam.gserviceaccount.com'
#credentials = ee.ServiceAccountCredentials(service_account, 'home\private.json')
#ee.Initialize(credentials)
import folium
from home.forms import CoordinatesForm
from .models import Coordenadas
from shopp.models import BusinessAddress

def coordinates_form(request):
    coordinates = Coordenadas.objects.all()
    form = CoordinatesForm()

    #if request.method == 'POST':
        #form = CoordinatesForm(request.POST)
        #if form.is_valid():
        #    form.save()
    #    return redirect("maps")
    context = {
        'coordinates': coordinates,
            #'form' : form,
    }
    return render(request, 'home/mapss.html', context)

def maps(request):
    business = BusinessAddress.objects.all().values()
    coordenadas = list(BusinessAddress.objects.values_list('lat','lon'))#
    cod = pd.DataFrame(business)
   
    #print(coordenadas)
    map = folium.Map(location=[cod.lat.mean(), cod.lon.mean()], zoom_start=13, control_scale=False)
    for index, location_info in cod.iterrows():
        folium.Marker([location_info["lat"], location_info["lon"]], popup=(location_info['businessname'], location_info['building'])).add_to(map)
    
    

    map = map._repr_html_()
    context = {
        'map': map, 'business': business

        }
    return render(request, 'home/map.html', context)

from .mixins import Directions
'''
Basic view for routing 
'''


@login_required
def home(request):
    return render(request, 'core/home.html')

class HomeView(TemplateView):
    template_name = 'home/home.html'
    model = Newsletter
    form_class = NewsletterForm

    def get(self, request):
        form = NewsletterForm()
        posts = Post.objects.all()
        homepages = Homepage.objects.all() 

        args = {
            'posts': posts, 'homepages': homepages, 'form': form
        }
        return render(request, self.template_name, args)

    def post(self, request):
        form = NewsletterForm(request.POST)
        if form.is_valid():
            newsletter = form.save(commit=False)
            newsletter.user = request.user
            newsletter.save()
            title = 'Thanks!!'
            confirm_message = "Thankyou for subscribing to our newsletter, Email received"
            context = {'title': title, 'confirm_message': confirm_message }
            
        return render(request, self.template_name, context)


@login_required
def change_friends(request, operation, pk):
    friend = User.objects.get(pk=pk)
    if operation == 'add':
        Friend.make_friend(request.user, friend)
        return redirect('Profile:shop')
    elif operation == 'remove':
        Friend.lose_friend(request.user, friend)
    return redirect('Profile:favouriteshops') 



class ContactView(CreateView):
    model = Contact
    form_class = ContactForm
    template_name = 'home/contact.html'
    success_url = reverse_lazy('shopp:product_list')

    def get(self, request):
        form = ContactForm()
        return render(request, self.template_name, {'form': form})

    def post(self,request):
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            contact.save()
            title = 'Thanks!!'
            confirm_message = 'Thanks for the message. We will get right back to you!'
            context = {'title': title, 'confirm_message': confirm_message}
        return render(request, self.template_name, context)
        #return redirect('shopp:product_list')



class PrivacyView(TemplateView):
    template_name = "home/privacy.html"

    def get(self, request):
        #form = PrivacyForm()
        privacy = Privacy.objects.all()#.order_by('-date')

        args = {'privacy': privacy }
        return render(request, self.template_name, args)

    def post(self, request):
        form = PrivacyForm()
        if form.is_valid():
            #privacy = form.save(commit=False)
            privacy = get_object_or_404(Privacy, id=id, slug=slug)
            privacy.user = request.user
            privacy.save()
            return redirect('home:privacy')
        args = {'privacy':privacy }
        return render(request, self.template_name, args)   


class TermsView(TemplateView):
    template_name = 'home/terms.html'

    def get(self, request):
        terms = Terms.objects.all()
        args = {'terms':terms }
        return render(request, self.template_name, args)

    def post(self, request):
        if form.is_valid():
            terms = get_object_or_404(Terms)
            terms.user = request.user
            terms.user()
            return redirect('home:terms')

        args = {'terms':terms}
        return render(request, self.template_name, args)

class AboutView(TemplateView):
    template_name = 'home/about.html'


    def get(self, request):
        aboutpages = Aboutpage.objects.all()

        args = {
            'aboutpages': aboutpages
        }
        return render(request, self.template_name, args)

#class MarkersMapView(TemplateView):
#    template_name = 'index.html'

    # Define a method for displaying Earth Engine image tiles on a folium map.
    #def get_context_data(self, **kwargs):

#        figure = folium.Figure()
        
        #create Folium Object
#        m = folium.Map(
#            location=[28.5973518, 83.54495724],
#            zoom_start=8
#        )

        #add map to figure
#        m.add_to(figure)

        
        #select the Dataset Here's used the MODIS data
#        dataset = (ee.ImageCollection('MODIS/006/MOD13Q1')
#                  .filter(ee.Filter.date('2019-07-01', '2019-11-30'))
#                  .first())
#        modisndvi = dataset.select('NDVI')

        #Styling 
#        vis_paramsNDVI = {
#            'min': 0,
#            'max': 9000,
#            'palette': [ 'FE8374', 'C0E5DE', '3A837C','034B48',]}

        
        #add the map to the the folium map
#        map_id_dict = ee.Image(modisndvi).getMapId(vis_paramsNDVI)
       
        #GEE raster data to TileLayer
#        folium.raster_layers.TileLayer(
#                    tiles = map_id_dict['tile_fetcher'].url_format,
#                    attr = 'Google Earth Engine',
#                    name = 'NDVI',
#                    overlay = True,
#                    control = True
#                    ).add_to(m)

        
        #add Layer control
#        m.add_child(folium.LayerControl())
       
        #figure 
#        figure.render()
         
        #return map
        #return {"map": figure}


class MarkersMapView(TemplateView):
    """Markers map view."""

    template_name = "home/map.html"

def logout(request):
    if request.method=="POST":
        auth.logout(request)
        return redirect('Profile:shop')

login/views/client.py
from django.contrib import messages
from django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator



from login.decorators import client_required
from login.models import  Client, User
from django.views.generic import TemplateView , CreateView
from login.forms import  ClientSignUpForm


class ClientSignUpView(CreateView):
    template_name = 'registration/signup_form.html'
    model = Client
    form_class = ClientSignUpForm

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'client'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('shopp:product_list')

login/templates/base.html
 {% load static %}
 <!DOCTYPE html>
 <html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    {% comment %} <meta name="viewport" content="width=device-width, initial-scale=1"> {% endcomment %}
    
   
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

     {% comment %} <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjj5OT0bp2DdeZ0r59OBcduelJWX-SAA0&libraries=places&callback=initMap&solution_channel=GMP_QB_addressselection_v1_cABC" async defer></script> {% endcomment %}

    {% comment %} <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% endcomment %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'login/style.css'%}" type="text/css">
    <link rel="shortcut icon" type="image/png" href="https://img.freepik.com/free-vector/eco-green-buildings-icons-skyscrapers-isolated-sketch-v_98292-4489.jpg?w=740&t=st=1667124371~exp=1667124971~hmac=d1eb7131d31eb2a9761fe127c56d2a18e5078b4989a4eb2ed36b401bf2501da3">
 
      {% block head %}
      <title>base</title>
    
      {% endblock %}
      
</head>
<body>



                <nav class="navbar sticky-top navbar-expand-lg navbar-light " style="background-color:#039366">
                        <a class="navbar-brand text-white" style="color:FF0000" href="{% url 'shopp:product_list'  %}"><h6><b>Favourite</b></h6></a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                      
                        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          
                              
                                <li class="nav-item active mr-auto">
                                        <a class="nav-link text-white" href="{% url 'shopp:businessadress_form'  %}">Post</a>
                                  </li>
                                <li class="nav-item active mr-auto">
                                        <a class="nav-link text-white" href="{% url 'Profile:favouriteshops'  %}">All Agents</a>
                                  </li>
                                <li class="nav-item active mr-auto">
                                        <a class="nav-link text-white" href="{% url  'Profile:about' %}">About</a>
                                  </li>

                          </ul>


                            


                                      <!-- Example single small button -->
                                <li class="nav item">
                                  {% if user.is_authenticated %}
                                  <div class="dropdown">
                           
                                    <div class="btn-group">
                                                <button class="btn text-white btn-sm  dropdown-toggle" style="background-color:#039366" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                        Profile
                                                </button>
                                                <div class="dropdown-menu">
                                                     {% if user.is_shop %}
                                                          <a class="dropdown-item"  href="{% url  'Profile:Shopadmin' %}">Business Account</a>
                             
                                                        {% else %}
                                                          <a class="dropdown-item"  href="{% url  'Profile:Shopadmin' %}">Business Account</a>
                                                        {% endif %}
                                                    
                                                    <a class="dropdown-item" href="{% url 'login:profile'  %}">Account</a>
                                                    <a class="dropdown-item" href="{% url 'home:terms'  %}">Terms</a>
                                                    
                                                    <a class="dropdown-item" href="{% url 'login:logout' %}">Logout</a>

                                                </div>
                                                </div>
                                              {% else  %}
                                      <div class="dropdown">
                           
                                    <div class="btn-group">
                                                <button class="btn  text-white btn-sm  dropdown-toggle" style="background-color:#039366" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                        Account
                                                </button>
                                                <div class="dropdown-menu">
                                                  
                                                    <a class="dropdown-item" href="{% url 'login'  %}">sign in</a>
                                                    <a class="dropdown-item" href="{% url 'signup'  %}">sign up</a>
                                                    {% comment %} <a class="dropdown-item" href="{ % url 'login:reset_password'  %}">reset-password </a> {% endcomment %}
                                                    <a class="dropdown-item" href="{% url 'login:logout' %}">Logout</a>

                                                </div>
                                                </div>
                               
                                               {% endif %}
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                
                  
                  <a class="dropdown-item" href="{% url 'login:profile' %}">
                            View Profile                 
                  </a>
                 
                                
                                {% if user.is_shop %}
                                    <a class="dropdown-item"  href="{% url  'Profile:Shopadmin' %}">Resident admin</a>
                                 
                                
                                    
                                  {% else %}

                                  {% endif %}
                                 




                  
                 
              </div>
            </div>
          </li>
              
              
<br>



                                <form   class="form-inline my-2 my-lg-0" action='{% url 'shopp:product_list' %}'>
                                
                                   
                                        <input  type="search" class="form-control outline-info btn-sm mr-sm-2"  placeholder="Search" name='q'>
                                     {% csrf_token %}      
                                        <button class="btn btn-light btn-sm btn my-2 my-sm-0" type="submit">Search</button>
                                      </form>
                                
                        </div>
                      </nav>  
       
    {% block body%}
    <h1>Base</h1>
    {% endblock %}





    <!-- Optional JavaScript -->
   <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
{% comment %} <script>
    "use strict";

    function initMap() {
      const CONFIGURATION = {
        "ctaTitle": "Checkout",
        "mapOptions": {"center":{"lat":37.4221,"lng":-122.0841},"fullscreenControl":true,"mapTypeControl":false,"streetViewControl":true,"zoom":11,"zoomControl":true,"maxZoom":22},
        "mapsApiKey": "AIzaSyCjj5OT0bp2DdeZ0r59OBcduelJWX-SAA0",
        "capabilities": {"addressAutocompleteControl":true,"mapDisplayControl":true,"ctaControl":true}
      };
      const componentForm = [
        'location',
        'locality',
        'administrative_area_level_1',
        'country',
        'postal_code',
      ];

      const getFormInputElement = (component) => document.getElementById(component + '-input');
      const map = new google.maps.Map(document.getElementById("gmp-map"), {
        zoom: CONFIGURATION.mapOptions.zoom,
        center: { lat: 37.4221, lng: -122.0841 },
        mapTypeControl: false,
        fullscreenControl: CONFIGURATION.mapOptions.fullscreenControl,
        zoomControl: CONFIGURATION.mapOptions.zoomControl,
        streetViewControl: CONFIGURATION.mapOptions.streetViewControl
      });
      const marker = new google.maps.Marker({map: map, draggable: false});
      const autocompleteInput = getFormInputElement('location');
      const autocomplete = new google.maps.places.Autocomplete(autocompleteInput, {
        fields: ["address_components", "geometry", "name"],
        types: ["address"],
      });
      autocomplete.addListener('place_changed', function () {
        marker.setVisible(false);
        const place = autocomplete.getPlace();
        if (!place.geometry) {
          // User entered the name of a Place that was not suggested and
          // pressed the Enter key, or the Place Details request failed.
          window.alert('No details available for input: \'' + place.name + '\'');
          return;
        }
        renderAddress(place);
        fillInAddress(place);
      });

      function fillInAddress(place) {  // optional parameter
        const addressNameFormat = {
          'street_number': 'short_name',
          'route': 'long_name',
          'locality': 'long_name',
          'administrative_area_level_1': 'short_name',
          'country': 'long_name',
          'postal_code': 'short_name',
        };
        const getAddressComp = function (type) {
          for (const component of place.address_components) {
            if (component.types[0] === type) {
              return component[addressNameFormat[type]];
            }
          }
          return '';
        };
        getFormInputElement('location').value = getAddressComp('street_number') + ' '
                  + getAddressComp('route');
        for (const component of componentForm) {
          // Location field is handled separately above as it has different logic.
          if (component !== 'location') {
            getFormInputElement(component).value = getAddressComp(component);
          }
        }
      }

      function renderAddress(place) {
        map.setCenter(place.geometry.location);
        marker.setPosition(place.geometry.location);
        marker.setVisible(true);
      }
    }
    </script> {% endcomment %}


    

</body>
</html>

login/templates/home.html
{% extends 'base.html' %}

{% block body %}
  <h2>Welcome to Resident  <span class="icon-emo-happy"></span></h2>
  <p class="lead">
    If you already have an account, go ahead and <a href="{% url 'login' %}">log in</a>. If you are new , get started
    by creating a <a href="{% url 'client_signup' %}">Resident account</a> or a <a href="{% url 'shop_signup' %}">Business account</a>.
  </p>
  <hr>
  
{% endblock body %}