estate/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include ,path ,re_path


from login.views import  client , shop, login

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('home/',include('home.urls',namespace='home')),
    #path('main/',include('main.urls',namespace='main')),
    re_path(r'', include('shopp.urls',namespace='shop')),
    path('', include('login.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', login.SignUpView.as_view(), name='signup'),
    path('accounts/signup/client/', client.ClientSignUpView.as_view(), name='client_signup'),
    path('accounts/signup/shop/', shop.ShopSignUpView.as_view(), name='shop_signup'),
    #path('shopp/',include('shopp.urls',namespace='shop')),
    path('Profile/',include('Profile.urls',namespace='Profile')),
    
    
]
   
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   

home/urls.py
from django.conf.urls import url
from django.urls import include, re_path
#from home.views import 
from django.contrib.auth import views as auth_views
from . import views as myapp_views
from home import views
from . import views 
from home.views import ContactView, PrivacyView, TermsView, MarkersMapView, AboutView, HomeView, coordinates_form, maps #, map, route


app_name = 'home'


urlpatterns = [
    re_path(r'^$', HomeView.as_view(), name='home'),
    re_path(r'^privacy/', PrivacyView.as_view(), name='privacy' ),
    re_path(r'^terms/', TermsView.as_view(), name='terms'),
    #re_path(r"^map/", MarkersMapView.as_view(),name="map"),
    #re_path(r'^route/', views.route, name="route"),
    re_path(r'^coordinates-form/',views.coordinates_form, name = 'coordinates-form'),
    re_path(r'^map/', views.maps, name="map"),
    
    re_path(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$', 
            views.change_friends, name='change_friends'),
    re_path('contact/', ContactView.as_view(), name='Contact'),
    re_path(r'^about/', AboutView.as_view(), name='about'),

  
]

shopp/urls.py
from django.conf.urls import include, re_path
from .import views
from .views import  AbouttView,  all_shops
from shopp.views import Product_detailView, ShopsView, delete_view, product_delete_view, BusinessAdressFormView,Product_detailView,ResidentAddressFormView
#from Profile.views import ProductDeleteView


app_name = 'shopp'

urlpatterns = [
    re_path(r'^$', views.product_list, name='product_list'),
    #re_path(r'^(?P<id>\d+)/delete/', views.product_list, name='product_list'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    re_path('^<int:id>/delete/$', product_delete_view, name='product_delete'),
    re_path(r'^$', ShopsView.as_view(), name='shops'),
    re_path('shopp/businessadress_form/', BusinessAdressFormView.as_view(), name='businessadress_form'),
    re_path('shopp/residentadressform/', ResidentAddressFormView.as_view(), name='residentadressform'),
    re_path(r'^(?P<uniqueadress>\d+)/(?P<slug>[-\w]+)/$', Product_detailView.as_view(), name='business_detail'),
    #re_path(r'^(?P<pk>\d+)/(?P<slug>[-\w]+)/$', Product_detailView.as_view(), name='business_detail_with_pk'),
    re_path(r'^about_uss/$',views.AbouttView, name='about_uss'),
    re_path(r'^contact_us/$', views.contact_us , name='contact_us'),
    re_path(r'^registershop/$', views.registershop, name='registershop'), 
    
    re_path(r'^search/$', views.search, name='search'),  
    re_path(r'^all_shops/$', views.all_shops, name='all_shops'),
    #re_path(r'^<int:product_pk>/(?P<slug>[-\w]+)/delete/',ProductDeleteView.as_view(), name='product_delete'),
    

    
]

shopp/forms.py
from django import forms
from login.models import User
from shopp.models import BusinessAddress, ResidentAddress



PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

class ShopCreationForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    

    class Meta:
        #model = Shop
        fields = (
            'shop_name',
            'shop_contact',
            'last_name',
            ' shop_email',
            
        )
    def save(self, commit=True):
        User = super(ShopCreationForm, self).save(commit=False)
        User.shop_name = self.cleaned_data['first_name']
        User.shop_name = self.cleaned_data['last_name']
        User.shop_email = self.cleaned_data['email']

        if commit:
            User.save()

        return User



class BusinessAdressForm(forms.ModelForm):
    
    class Meta:
        model = BusinessAddress
        
        
        fields = [
            #'businessname',
            'category',
            'county',
            'building', 
            'landmark',
            'floor_no',
            'street',
            'door_no',
            'image',
            'image1',
            'image2',
            
            #'contact',
            #'lat',
            #'lon'
            #'geolocation'    
        ]

        
    def save(self, user=None):
        businessname = super(BusinessAdressForm, self).save(commit=False)
        if user:
            businessname.user = user
        businessname.save()
        return businessname


class ResidentAddressForm(forms.ModelForm):
    
    class Meta:
        model = ResidentAddress
        
        
        fields = [
            
            'county',
            'building', 
            'landmark',
            'floor_no',
            'door_no',
            'county',
            'image',
            'description',
            'lat',
            'lon'
            #'geolocation'    
        ]

        
    def save(self, user=None):
        building = super(ResidentAddressForm, self).save(commit=False)
        if user:
            building.user = user
        building.save()
        return building

login/views/shop.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator


from login.decorators import client_required, shop_required
from login.models import Shop, User
from django.views.generic import TemplateView , CreateView
from login.forms import ShopSignUpForm


class ShopSignUpView(CreateView):
    template_name = 'registration/signup_form.html'
    model = Shop
    form_class = ShopSignUpForm

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'shop'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('shop:product_list')

shopp/views.py
from django.shortcuts import render
from estate import settings
from login.decorators import shop_required, client_required
from django.views.generic import (ListView, UpdateView, CreateView, FormView, DeleteView)
# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView
from shopp.models import Category# Product 
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render
from django.db.models import Q
from login.models import User 
from shopp.forms import BusinessAdressForm ,ResidentAddressForm#,ShopCreationForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponse
from home.models import Friend
from django.contrib.auth.mixins import LoginRequiredMixin
from shopp.models import BusinessAddress,ResidentAddress
from django.urls import reverse_lazy


def all_shops(request):
    #args = {'user': request.user}
    return HttpResponse('kdkdl')



## this is the view to the shop don't edit  ##
#@login_required
def product_list(request, category_slug=None ,pk=None):
    
    category = None
    categories = Category.objects.all()
    business = BusinessAddress.objects.all()
    users = User.objects.exclude(id=request.user.id).order_by('date_joined')

    query = request.GET.get('q')
    if query:
        business = BusinessAddress.objects.filter(
            Q(businessname__icontains=query)|
            Q(building__icontains=query)|
            Q(street__icontains=query)|
            Q(county__icontains=query)
        )
        users = User.objects.filter(
            Q(is_shop__icontains=query)
        )
    else:
        business = BusinessAddress.objects.all()

    

#    friend = Friend.objects.get(current_user=request.user)
#    friends = friend.users.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        #products = products.filter(category=category)
        business = BusinessAddress.filter(category=category)
    
    paginator = Paginator(business,44)
    page = request.GET.get('page')
    try:
        business = paginator.page(page)
    except PageNotAnInteger:
        business = paginator.page(1)
    except EmptyPage:
        business = paginator.page(paginator.num_pages)
    index = business.number -1
    max_index = len(paginator.page_range)
    start_index = index -5 if index >= 5 else 0 
    end_index = index + 5 if index <=max_index  -5 else max_index
    page_range = paginator.page_range[start_index:end_index]

    #paginator = Paginator(users, 14)
    page = request.GET.get('page')
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)

    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    index = users.number -1
    max_index = len(paginator.page_range)
    start_index = index -5 if index >= 5 else 0 
#    end_index = index + 5 if index <=max_index  -5 else max_index
#    page_range = paginator.page_range[start_index:end_index]

    return render(request, 'shop/list.html',{'category': category,
    'categories':categories, 'business': business ,'users': users  ,# 'friends': friends,
     'page_range': page_range })

#end of shop view


#@method_decorator(login_required, name='dispatch')
class Product_detailView(TemplateView):
    template_name = 'shop/detail.html'

    def get(self, request, uniqueadress , slug ,pk=None):

        if pk:
            user = User.objects.get(pk=pk)
            business = get_object_or_404(BusinessAddress,businessname=businessname, slug=slug, uniqueadress=True)
        else:
            user = request.user
            business = get_object_or_404(BusinessAddress, uniqueadress=uniqueadress) 

        args = {'business': business, 'user': user }
        
        return render(request,self.template_name, args) 
                
class Resident_detailView(TemplateView):
    template_name = 'Profile/detail.html'

    def get(self, request, uniqueadress , date ,pk=None):

        if pk:
            user = User.objects.get(pk=pk)
            resident = get_object_or_404(ResidentAddress,uniqueadress=uniqueadress, user=user)
        else:
            user = request.user
            resident = get_object_or_404(ResidentAddress, uniqueadress=uniqueadress) 

        args = {'resident': resident, 'user': user }
        
        return render(request,self.template_name, args) 
      

class Contactview(TemplateView):
    template_name = 'shop/contact_us.html'


def contact_us(request):
    form_class = ContactForm(request.POST or None)

    return render(request, 'shop/contact_us.html', {
        'form': form_class,
    })


def AbouttView(request):
 #   #args = {'user': request.user}
    return render(request,('shop/about_uss.html'))   

def registershop(request):
    if request.method == 'POST':
        form = ShopCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/shop/shopp')
        else:
            form = ShopCreationForm()

           # args = ('form': form)
            return render(request, 'shop/reg_form.html')#, args)




def search(request):
    product_list = Product.objects.all()
    product_filter = ProductFilter(request.GET, queryset=product_list)
    return render(request, 'shop/search/product_list.html', {'filter': product_filter})

class ShopsView(TemplateView):
    template_name = 'shop/shops.html'
    

    def get(self, request):
        
        
        users = User.objects.exclude(id=request.user.id)
        friend = Friend.objects.get(current_user=request.user)
        friends = friend.users.all()

        query = request.GET.get('q')
        if query:

            users = User.objects.filter(
            Q(shop_name__icontains=query)#|
#            Q(user__username__icontains=query)|
#            Q(description__icontains=query)|
            #Q(created__icontains=query)
        )


        args = {  'users': users,
         'friends': friends
        }
        return render(request, self.template_name, args)


def product_delete_view(request, id):
    obj = get_object_or_404(Product, id=id)

    if request.method == "POST":
        obj.delete()
        return redirect('../../')
    context = {
        "object": obj
    }
    return render(request, "shop/product_delete.html", context)




def delete_view(request, id):
    item_to_delete = Product.objects.filter(pk=id)
    if item_to_delete.exists():
        if request.user == item_to_delete[0].user:
            item_to_delete[0].delete()
    return redirect('/')



#@method_decorator([login_required, shop_required], name='dispatch')
class BusinessAdressFormView(LoginRequiredMixin, CreateView):
    model = BusinessAddress
    form_class = BusinessAdressForm
    template_name = 'shop/businessadress_form.html'
    success_url = reverse_lazy('Profile:Shopadmin')

 
    def form_valid(self, form):
       
        businessname = form.cleaned_data.get('name')
        building = form.cleaned_data.get('building')
        image = form.cleaned_data.get('image')
        county = form.cleaned_data.get('county')
        
        form.save(self.request.user)
        return super().form_valid(form)


#@method_decorator([login_required, shop_required], name='dispatch')
class ResidentAddressFormView(LoginRequiredMixin, CreateView):
    model = ResidentAddress
    form_class = ResidentAddressForm
    template_name = 'shop/residentadressform.html'
    success_url = reverse_lazy('login:profile')

 
    def form_valid(self, form):
       
        businessname = form.cleaned_data.get('name')
        building = form.cleaned_data.get('building')
        image = form.cleaned_data.get('image')
        county = form.cleaned_data.get('county')
        
        form.save(self.request.user)
        return super().form_valid(form)

shopp/templates/shop/businessadress_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{{%  block head %}
<title>Create a Post</title>
{% endblock head  %}}


{% block body %}

<br/>


        <!--section 2-->
    <div class="container" >
    
    
    
    
        
            <div class="container">
               <div class="container"> 
               <div class="container">
               <div class="container"> 
               <div class="container">
               <div class="container"> 
               <div class="container">
                            <form method="POST" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {{ form|crispy }}
                                        <button type="submit" class="btn btn-info">Post</button>
                                    </form>
                </div>
                </div>
                </div>
                </div>
                </div>
                </div>
                </div>
            </div>     
        
    </div>







</div>

<br/>
<hr/>     
<footer class="container">
      <p class="float-right"><a href="#">Back to top</a></p>
      <p>&copy; Agents and Realtors &middot; 2022 <a href="#">Privacy</a>  <a href="#">Terms</a></p>
    </footer>   


{% endblock body %}

shopp/templates/shop/contact_uss.html
{% extends "base.html" %}  
{ {% block head %}
<title>Contact</title>
{% endblock head %}}
{% block body %}
{% endblock body %}

shopp/templates/shop/detail.html
{% extends "base.html" %}
{% load static %}

{{%  block head %}
<title>{{ business.name }}</title>
{% endblock head  %}}

{% load social_share %}
{% block body %}





<br>
<div class="container">
<h3>{{ business.category }},    Agency: {{ business.user.username }}</h3> 


  <h5 class="text-right"><a href="{{ product.category.get_absolute_re_path }}"><cite title="Source Title"> {{ product.category }}</cite></a></h5>
  
  <h2 class="featurette-heading"> <span class="text-muted"></span></h2>
</div>
<br/>


    
    <div class="container">


    
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% if business.image %}
                              {{ business.image.url }}{% else %}
                              https://images.unsplash.com/photo-1599619351208-3e6c839d6828?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=872&q=80{% endif  %}" class="d-block w-100" alt="..." 
                              style="width:69.25rem; height:26.5rem;">
      <div class="carousel-caption d-none d-md-block">
         <p>Welcome to my website My name is </p>
        <h5 class="display-4"><b>{{ post.post }}</b></h5>
        
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% if business.image %}
                              {{ business.image.url }}{% else %}
                              https://images.unsplash.com/photo-1599619351208-3e6c839d6828?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=872&q=80{% endif  %}" class="d-block w-100" alt="..." style="
                  width:69.25rem; height:26.5rem;">
      <div class="carousel-caption d-none d-md-block">
        <h5></h5>
        <p></p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% if business.image %}
                              {{ business.image.url }}{% else %}
                              https://images.unsplash.com/photo-1599619351208-3e6c839d6828?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=872&q=80{% endif  %}" class="d-block w-100" alt="..." style="
                  width:69.25rem; height:26.5rem;">
      <div class="carousel-caption d-none d-md-block">
        <h5></h5>
        <p></p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>








          <div class="border-light card mb-3">
  
  <div class="card-body">
    <h5 class="card-title"><b> {{ business.category }}</b> </h5>
            <blockquote class="blockquote text-justify"> <p class="mb-0"> {{ business.street|linebreaks }} </p></blockquote>
            <br>

                                  


           
            <br>
            <blockquote class="blockquote text-justify"> <h4 class="mb-0">Floor Number:  {{ business.floor_no|linebreaks }}</h4></blockquote>
            <blockquote class="blockquote text-justify"> <p class="mb-0">landmark:  {{ business.landmark|linebreaks }}</p></blockquote>
    


                                           
                                           
                                              
                                           <b>

                                            <b>
                                            {% post_to_twitter text_to_post object_or_url %}
                                            {% post_to_facebook object_or_url %}
                                            {% post_to_whatsapp object_or_url %}
                                            {% post_to_linkedin object_or_url %}
                                            </b>
    
  </div>

</div>





      






      
          
        
         </div>           
    </div>

   









<div class="footer" style="color:olive;">
        <hr/>
        <div class="copyright">
          <div class="container">
            <span>Favourite  &copy; 2022</span>
        </div>
      </div>
    </div>












{% endblock body %}






<br>
<div class="container">
 <a href="">
<h3>{{ business.category }},    Agency: {{ business.user.username }}</h3> 
</a>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% if business.image %}
                              {{ business.image.url }}{% else %}https://images.unsplash.com/photo-1599619351208-3e6c839d6828?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=872&q=80{% endif  %} "  style=" height:25.5rem;" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% if business.image %}
                              {{ business.image.url }}{% else %}https://images.unsplash.com/photo-1599619351208-3e6c839d6828?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=872&q=80{% endif  %}"   style=" height:25.5rem;" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% if business.image %}
                              {{ business.image.url }}{% else %}https://images.unsplash.com/photo-1599619351208-3e6c839d6828?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=872&q=80{% endif  %}" style=" height:25.5rem;" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-target="#carouselExampleIndicators" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-target="#carouselExampleIndicators" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </button>
</div>















 

          <div class="card" style="">
                
                 
                   <div class="card-body">
                      
                      <h6 class="card-text"><b> County:</b> {{ business.county }}</h6>
                      <h6 class="card-title"><b> Building:</b>{{ business.building }}</h6>
                      <h6 class="card-title"></h6>
                      
                      

                                            
                                            
                                            


                    </div>
                </div>
         </div>

<div class="footer" style="color:olive;">
        <hr/>
        <div class="copyright">
          <div class="container">
            <span>Favourite &copy; </span>
        </div>
      </div>
    </div>

shopp/templates/shop/list.html
{% extends "base.html" %} 
{% load crispy_forms_tags %} 
{ {% block head %}
    <title>Favourite</title>
{% endblock head %}}

{% block body %}


<br/>




    <div class="container">
    {% for busines in business %}
                                        
                                <span class="separator">
                                    <div class="row" style="width: 18.2rem; height:18.4rem; display:table-row-group;"  >
                                        
                                        <div class="card-body border-grey mb-3 shadow" >
                                            <a href="{{ busines.get_absolute_re_path }}">
                                                <img src="{% if  busines.image %}{{  busines.image.url }}{% else %}https://images.unsplash.com/photo-1605475161596-c8ded579e67a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=386&q=80{% endif  %}" style="width: 18.2rem; height:13.5rem;">
                                            </a>
                                            <hr/>
                                            <div class="container">
                                            <div class="">
                                               <b>category:</b> {{ busines.category }}
                                              </div>
                                           <b>County:</b>{{ busines.county }}
                                           <div class="">
                                               <b> Landmark:</b> {{ busines.landmark }}
                                               
                                              </div>
                                              <b> by:</b> {{ busines.user.username }}
                                             
                                            
                                        </div>
                                            
                                            
                                      
                                       
                                        
                                        </div>
                                        </div>
                                    </span>  
                                    {% endfor %}      
                           

                </div>





{% include "pagination.html" %} 

      <hr/>
     
     
      <footer class="container">
            <p class="float-right"><a href="#">Back to top</a></p>
              
            <p>Favourite Developers &copy; 2022 <a href="{% url 'home:privacy' %}">Privacy</a> Favourite <a href="{% url 'home:terms' %}">Terms</a> <a href="{% url 'home:Contact' %}">contact us</a>
          </footer>   
    
   
    

{% endblock body %}

shopp/templates/shop/product_delete.html
{% extends "base.html" %}
{% load static %}

{{%  block head %}
<title>delete product</title>
{% endblock head  %}}

{% block body %}

<form action='' method=''>
      {% csrf_token %}
      <h3>Do you want to delete the product "{{ product.name }}"?</h3>
      <p><input type='submit' value='Yes' /><a href='../'>Cancel </p>
</form>


{% endblock body %}

shopp/templates/shop/product_form.html
{% extends "base.html" %}  
{% load crispy_forms_tags %}
{% load i18n %}
{ {% block head %}
    <title>Add Product</title>
{% endblock head %}}

{% block body %}
<nav class="navbar navbar-expand text-white shadow navbar " style="background-color:teal;">Add Product</nav>
<br/>


<div class="row">
        <div class="col-12 col-sm-6 col-md-6">
            <div class="container">
                <div class="card shadow-sm">
                        <div class="card-body">                      
            <div class="container">

                    <div class="alert alert-primary" role="alert">
                        <p> checkout! </p>
                    </div>

                {% if form %}
                <form method="post" role="form" action="" class="">
                        {% csrf_token %}
                        {{ form|crispy }}
                
                <p><input type="submit" class="btn btn-sm btn-info" value="Place order"></p>
                </form> 
                {% endif %}
            </div>             
        </div>
    </div>
</div> 
</div>
        <!--section 2-->
    <div class="col-3 col-md col-md-6" >
    
    
    
    
        
            <div class="container">
                
               <form method="POST">
                         {% csrf_token %}
                         {{ form|crispy }}
                        <button type="submit" class="btn btn-success">Create Product</button>
                    </form>
         </div>
        </div>     
        
    </div>







</div>

<br/>
<hr/>     
<footer class="container">
      <p class="float-right"><a href="#">Back to top</a></p>
      <p>&copy; Favourite.inc &middot; <a href="#">Privacy</a> Favourite <a href="#">Terms</a></p>
    </footer>   


{% endblock body %}

shopp/templates/shop/product_list.html
{% extends 'base.html' %}

{% block body %}
  <form method="get">
    {{ filter.form.as_p }}
    <button type="submit">Search</button>
  </form>
  <ul>
  {% for user in filter.qs %}
    <li>{{ user.username }} - {{ user.get_full_name }}</li>
  {% endfor %}
  </ul>
{% endblock %}

shopp/templates/shop/residentadressform.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{{%  block head %}
<title>Create a Resident Address</title>
{% endblock head  %}}


{% block body %}

<br/>

        <!--section 2-->
    <div class="container" >
    
    
    
    
        
            <div class="container">
               <div class=""> 
               <div class="container">
               <div class="container"> 
               <div class="container">
               <div class="container"> 
               <div class="container">
                            <form method="POST" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {{ form|crispy }}
                                        <button type="submit" class="btn btn-info">Create Resident Address</button>
                                    </form>
                </div>
                </div>
                </div>
                </div>
                </div>
                </div>
                </div>
            </div>     
        
    </div>







</div>

<br/>
<hr/>     
<footer class="container">
      <p class="float-right"><a href="#">Back to top</a></p>
      <p>&copy; Resident.inc &middot; 2022 <a href="#">Privacy</a>  <a href="#">Terms</a></p>
    </footer>   


{% endblock body %}